/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jni2DDE */

#ifndef _Included_Jni2DDE
#define _Included_Jni2DDE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jni2DDE
 * Method:    doDDE
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Jni2DDE_doDDE
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     Jni2DDE
 * Method:    initDDE
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Jni2DDE_initDDE
  (JNIEnv *, jobject, jint);

/*
 * Class:     Jni2DDE
 * Method:    connectDDE
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Jni2DDE_connectDDE
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Jni2DDE
 * Method:    queryDDE
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Jni2DDE_queryDDE
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Jni2DDE
 * Method:    disconnectDDE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jni2DDE_disconnectDDE
  (JNIEnv *, jobject);

/*
 * Class:     Jni2DDE
 * Method:    uninitDDE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jni2DDE_uninitDDE
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
